/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountIdentityComponent: typeof import('./src/components/auth/forgetPasswordComponents/AccountIdentityComponent.vue')['default']
    AccountIdentityComPonent: typeof import('./src/components/auth/forgetPasswordComponents/AccountIdentityComPonent.vue')['default']
    Admin: typeof import('./src/components/admin/admin.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    EmailLoginComponent: typeof import('./src/components/auth/loginComponents/EmailLoginComponent.vue')['default']
    EmailRegisterComponent: typeof import('./src/components/auth/registerComponents/EmailRegisterComponent.vue')['default']
    Login: typeof import('./src/components/auth/login.vue')['default']
    LoginButtonComponent: typeof import('./src/components/auth/loginComponents/LoginButtonComponent.vue')['default']
    LoginComponent: typeof import('./src/components/system/loginComponents/LoginComponent.vue')['default']
    LoginComponents: typeof import('./src/components/system/LoginComponent.vue')['default']
    LoginWaysComponent: typeof import('./src/components/auth/loginComponents/LoginWaysComponent.vue')['default']
    PageFooterComponenet: typeof import('./src/components/system/PageFooterComponenet.vue')['default']
    PasswordLoginComponent: typeof import('./src/components/auth/loginComponents/PasswordLoginComponent.vue')['default']
    PhoneRegisterComponent: typeof import('./src/components/auth/registerComponents/PhoneRegisterComponent.vue')['default']
    PhoneRegiterComponent: typeof import('./src/components/auth/registerComponents/PhoneRegiterComponent.vue')['default']
    PhoneRegitserComponent: typeof import('./src/components/auth/registerComponents/PhoneRegitserComponent.vue')['default']
    RegisterButtonComponent: typeof import('./src/components/auth/registerComponents/RegisterButtonComponent.vue')['default']
    RegisterIdentitySelectComponent: typeof import('./src/components/auth/registerComponents/RegisterIdentitySelectComponent.vue')['default']
    RegisterIdentitySelectCompont: typeof import('./src/components/auth/registerComponents/RegisterIdentitySelectCompont.vue')['default']
    ResetPasswordComponent: typeof import('./src/components/auth/forgetPasswordComponents/ResetPasswordComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepsComponent: typeof import('./src/components/auth/forgetPasswordComponents/StepsComponent.vue')['default']
    VerifyIdentityComponent: typeof import('./src/components/auth/forgetPasswordComponents/VerifyIdentityComponent.vue')['default']
    WechatLoginComponent: typeof import('./src/components/auth/loginComponents/WechatLoginComponent.vue')['default']
    WechatRegisterComponent: typeof import('./src/components/auth/registerComponents/WechatRegisterComponent.vue')['default']
    WxLoginComponent: typeof import('./src/components/system/loginComponents/wxLoginComponent.vue')['default']
  }
}
