/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Admin: typeof import('./src/components/admin/admin.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Login: typeof import('./src/components/auth/login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    System: typeof import('./src/components/system/system.vue')['default']
  }
}
